"""orderInfo-orderList change

Revision ID: 1f3d36690113
Revises: 474adf8418a0
Create Date: 2023-10-05 17:56:20.199719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3d36690113'
down_revision = '474adf8418a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderInfo', sa.Column('order_status', sa.String(), nullable=False))
    op.add_column('OrderInfo', sa.Column('payment_status', sa.String(), nullable=False))
    op.drop_column('OrderInfo', 'operation_code')
    op.drop_column('OrderList', 'operation_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderList', sa.Column('operation_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('OrderInfo', sa.Column('operation_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('OrderInfo', 'payment_status')
    op.drop_column('OrderInfo', 'order_status')
    # ### end Alembic commands ###
