"""orderInfo-orderList fix

Revision ID: 474adf8418a0
Revises: d595de0641a8
Create Date: 2023-05-12 09:16:50.973172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474adf8418a0'
down_revision = 'd595de0641a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('OrderList_order_info_id_fkey', 'OrderList', type_='foreignkey')
    op.create_foreign_key(None, 'OrderList', 'OrderInfo', ['order_info_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'OrderList', type_='foreignkey')
    op.create_foreign_key('OrderList_order_info_id_fkey', 'OrderList', 'OrderInfo', ['order_info_id'], ['order_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
