"""create OrderInfo and OrderList

Revision ID: 512d2a18c951
Revises: 13e1880f0644
Create Date: 2023-04-15 18:17:03.727158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512d2a18c951'
down_revision = '13e1880f0644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderInfo',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('operation_code', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['Client.client_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('OrderList',
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_info_id', sa.Integer(), nullable=True),
    sa.Column('operation_code', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.item_id'], ),
    sa.ForeignKeyConstraint(['order_info_id'], ['OrderInfo.order_id'], ),
    sa.PrimaryKeyConstraint('order_list_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderList')
    op.drop_table('OrderInfo')
    # ### end Alembic commands ###
