"""orderInfo-orderList cascade delete

Revision ID: d595de0641a8
Revises: 25f729f9bc0d
Create Date: 2023-05-11 23:11:26.486463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd595de0641a8'
down_revision = '25f729f9bc0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('OrderList_order_info_id_fkey', 'OrderList', type_='foreignkey')
    op.create_foreign_key(None, 'OrderList', 'OrderInfo', ['order_info_id'], ['order_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'OrderList', type_='foreignkey')
    op.create_foreign_key('OrderList_order_info_id_fkey', 'OrderList', 'OrderInfo', ['order_info_id'], ['order_id'])
    # ### end Alembic commands ###
